image: devfactory/workspace-full:latest
arch: arm

# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - init: echo 'init script' # runs during prebuild
    command: |
      pip install -r requirements.txt
      python api.py
# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 5000
    visibility: public
    onOpen: open-browser
